#!/bin/bash

networks=$(nmcli device wifi list | awk 'NR>1 {print $2 " - " $3 " - " $8}')
selected=$(echo "$networks" | rofi -dmenu -i -p "Select Network")

if [ -n "$selected" ]; then
  ssid=$(echo $selected | awk '{print $1}')
  nmcli device wifi connect "$ssid"
fi
